-- MySQL Script generated by MySQL Workbench
-- Mon Aug 30 22:02:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dhtube1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dhtube1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dhtube1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dhtube1` ;

-- -----------------------------------------------------
-- Table `dhtube1`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`avatar` (
  `ID_AVATAR` SMALLINT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `URL` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_AVATAR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`usuario` (
  `ID_USUARIO` BIGINT NOT NULL AUTO_INCREMENT,
  `E_MAIL` VARCHAR(100) NULL DEFAULT NULL,
  `CONTRASENA` VARCHAR(150) NULL DEFAULT NULL,
  `NOMBRE_USUARIO` VARCHAR(150) NULL DEFAULT NULL,
  `FECHA_NAC` DATE NULL DEFAULT NULL,
  `PAIS` VARCHAR(100) NULL DEFAULT NULL,
  `CODIGO_POSTAL` INT NULL DEFAULT NULL,
  `FK_AVATAR` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `FK_AVATAR` (`FK_AVATAR` ASC) VISIBLE,
  CONSTRAINT `FK_AVATAR`
    FOREIGN KEY (`FK_AVATAR`)
    REFERENCES `dhtube1`.`avatar` (`ID_AVATAR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`canal` (
  `ID_CANAL` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_CANAL` VARCHAR(150) NULL DEFAULT NULL,
  `DESCRIPCION_CANAL` TEXT NULL DEFAULT NULL,
  `FECHA_CREACION_CANAL` DATE NULL DEFAULT NULL,
  `FK_USUARIO_CANAL` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CANAL`),
  INDEX `FK_USUARIO_CANAL` (`FK_USUARIO_CANAL` ASC) VISIBLE,
  CONSTRAINT `FK_USUARIO_CANAL`
    FOREIGN KEY (`FK_USUARIO_CANAL`)
    REFERENCES `dhtube1`.`usuario` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`etiqueta` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`reaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`reaccion` (
  `ID_REACCION` SMALLINT NOT NULL AUTO_INCREMENT,
  `NOMBRE_REACCION` VARCHAR(50) NULL DEFAULT NULL,
  `ICONO` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_REACCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`video_publicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`video_publicado` (
  `ID_VIDEO` BIGINT NOT NULL AUTO_INCREMENT,
  `TITULO_VIDEO` VARCHAR(150) NULL DEFAULT NULL,
  `DESCRIPCION` TEXT NULL DEFAULT NULL,
  `TAMANO` FLOAT(6,3) NULL DEFAULT NULL,
  `NOMBRE_ARCHIVO` VARCHAR(200) NULL DEFAULT NULL,
  `DURACION_VIDEO` INT NULL DEFAULT NULL,
  `IMAGEN` VARCHAR(200) NULL DEFAULT NULL,
  `NUMERO_REPRODUCCIONES` BIGINT NULL DEFAULT NULL,
  `NUMERO_LIKES` BIGINT NULL DEFAULT NULL,
  `NUMERO_DISLIKES` BIGINT NULL DEFAULT NULL,
  `FECHA_HORA_POST` DATETIME NULL DEFAULT NULL,
  `FK_REACCIONES` SMALLINT NULL DEFAULT NULL,
  `FK_USUARIO` BIGINT NULL DEFAULT NULL,
  `ESTADO_VIDEO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_VIDEO`),
  INDEX `FK_REACCIONES` (`FK_REACCIONES` ASC) VISIBLE,
  INDEX `FK_USUARIO` (`FK_USUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_REACCIONES`
    FOREIGN KEY (`FK_REACCIONES`)
    REFERENCES `dhtube1`.`reaccion` (`ID_REACCION`),
  CONSTRAINT `FK_USUARIO`
    FOREIGN KEY (`FK_USUARIO`)
    REFERENCES `dhtube1`.`usuario` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`etiqueta_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`etiqueta_video` (
  `ID_ETIQUETA_VIDEO` SMALLINT NOT NULL AUTO_INCREMENT,
  `FK_VIDEO_PUBLICADO2` BIGINT NULL DEFAULT NULL,
  `FK_ETIQUETA` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ETIQUETA_VIDEO`),
  INDEX `FK_VIDEO_PUBLICADO2` (`FK_VIDEO_PUBLICADO2` ASC) VISIBLE,
  INDEX `FK_ETIQUETA` (`FK_ETIQUETA` ASC) VISIBLE,
  CONSTRAINT `FK_ETIQUETA`
    FOREIGN KEY (`FK_ETIQUETA`)
    REFERENCES `dhtube1`.`etiqueta` (`CODIGO`),
  CONSTRAINT `FK_VIDEO_PUBLICADO2`
    FOREIGN KEY (`FK_VIDEO_PUBLICADO2`)
    REFERENCES `dhtube1`.`video_publicado` (`ID_VIDEO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`playlist` (
  `ID_PLAYLIST` SMALLINT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PLAYLIST` VARCHAR(150) NULL DEFAULT NULL,
  `FECHA_CREACION_PLAYLIST` DATE NULL DEFAULT NULL,
  `FK_USUARIO_PLAYLIST` BIGINT NULL DEFAULT NULL,
  `ESTADO_PLAYLIST` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PLAYLIST`),
  INDEX `FK_USUARIO_PLAYLIST` (`FK_USUARIO_PLAYLIST` ASC) VISIBLE,
  CONSTRAINT `FK_USUARIO_PLAYLIST`
    FOREIGN KEY (`FK_USUARIO_PLAYLIST`)
    REFERENCES `dhtube1`.`usuario` (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`playlist_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`playlist_video` (
  `ID_AVATAR` SMALLINT NOT NULL AUTO_INCREMENT,
  `FK_PLAYLIST` SMALLINT NULL DEFAULT NULL,
  `FK_VIDEO_PUBLICADO` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_AVATAR`),
  INDEX `FK_PLAYLIST` (`FK_PLAYLIST` ASC) VISIBLE,
  INDEX `FK_VIDEO_PUBLICADO` (`FK_VIDEO_PUBLICADO` ASC) VISIBLE,
  CONSTRAINT `FK_PLAYLIST`
    FOREIGN KEY (`FK_PLAYLIST`)
    REFERENCES `dhtube1`.`playlist` (`ID_PLAYLIST`),
  CONSTRAINT `FK_VIDEO_PUBLICADO`
    FOREIGN KEY (`FK_VIDEO_PUBLICADO`)
    REFERENCES `dhtube1`.`video_publicado` (`ID_VIDEO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dhtube1`.`usuario_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dhtube1`.`usuario_video` (
  `ID_REGISTRO` INT NOT NULL AUTO_INCREMENT,
  `FK_ID_USUARIO` BIGINT NULL DEFAULT NULL,
  `FK_ID_VIDEO` BIGINT NULL DEFAULT NULL,
  `ESTADO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_REGISTRO`),
  INDEX `FK_ID_USUARIO` (`FK_ID_USUARIO` ASC) VISIBLE,
  INDEX `FK_ID_VIDEO` (`FK_ID_VIDEO` ASC) VISIBLE,
  CONSTRAINT `FK_ID_USUARIO`
    FOREIGN KEY (`FK_ID_USUARIO`)
    REFERENCES `dhtube1`.`usuario` (`ID_USUARIO`),
  CONSTRAINT `FK_ID_VIDEO`
    FOREIGN KEY (`FK_ID_VIDEO`)
    REFERENCES `dhtube1`.`video_publicado` (`ID_VIDEO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
